name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  docker-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-app .

      - name: Run container
        run: docker run devops-app
